[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["npm install -g pnpm@latest && npx pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["npx pnpm run build"]

[start]
cmd = "npx pnpm start"
